"""Audit exported SDK symbols against actual ARM bridges; never generate stubs.

The CSV is a declaration inventory, not implementations or structure layouts.
Reports stay on the host and add no firmware RAM or flash cost.
"""
import argparse
from collections import Counter
import csv
import hashlib
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]


def read_sdk(path):
    with path.open(encoding='utf-8-sig', newline='') as source:
        rows = list(csv.DictReader(source))
    version = next(row['name'] for row in rows if row['entry'] == 'Version')
    symbols = {row['name']: row for row in rows
               if row['entry'] in ('Function', 'Variable') and row['status'] == '+'}
    return version, rows, symbols


def bridges():
    header = (ROOT / 'components/flipper_application/arm_fap/arm_fap_vm.h').read_text()
    macro = header.split('#define ARM_FAP_IMPORTS(X)', 1)[1].split('typedef enum', 1)[0]
    return set(re.findall(r'X\((\w+)\)', macro))


def area(name):
    for prefix, category in (
        ('canvas_', 'Drawing'), ('elements_', 'Drawing'), ('view_', 'Views and dispatcher'),
        ('gui_', 'Views and dispatcher'), ('scene_', 'GUI modules'),
        ('submenu_', 'GUI modules'), ('widget_', 'GUI modules'), ('dialog', 'GUI modules'),
        ('text_', 'GUI modules'), ('variable_item', 'GUI modules'), ('furi_string_', 'Strings'),
        ('storage_', 'Storage'), ('flipper_format_', 'Storage'), ('stream_', 'Storage'),
        ('furi_hal_', 'Hardware HAL'), ('furi_', 'OS services'),
        ('nfc', 'NFC'), ('mf_', 'NFC'), ('iso', 'NFC'), ('subghz_', 'Sub-GHz'),
        ('infrared_', 'Infrared'), ('notification_', 'Notifications'), ('I_', 'Assets')):
        if name.startswith(prefix):
            return category
    return 'Other libraries and assets'


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--sdk', type=Path, default=ROOT / 'tests/fixtures/arm_api/api_symbols_88_2.csv')
    parser.add_argument('--baseline', type=Path, default=ROOT / 'tests/fixtures/arm_api/api_symbols_87_1.csv')
    parser.add_argument('--output', type=Path, default=ROOT / 'docs/arm_fap_api_coverage')
    args = parser.parse_args()
    version, rows, symbols = read_sdk(args.sdk)
    previous, _, baseline = read_sdk(args.baseline)
    supported = bridges()
    native_source = (ROOT / 'components/flipper_application/flipper_application/firmware_api.c').read_text()
    native = set(re.findall(r'\.address\s*=\s*\(uint32_t\)\s*(\w+)', native_source))
    failures = []
    for name in sorted(supported):
        old, new = baseline.get(name), symbols.get(name)
        if not old or not new or any(old[key] != new[key] for key in ('entry', 'type', 'params')):
            failures.append(name)
    if failures:
        raise SystemExit('Bridged declaration changed or absent; review ABI before enabling: ' + ', '.join(failures))
    report = []
    for name, row in sorted(symbols.items()):
        status = ('bridged_subset' if name in supported else
                  'native_export_needs_arm_bridge' if name in native else 'not_bridged')
        report.append(dict(name=name, kind=row['entry'], area=area(name), status=status,
                           return_or_variable_type=row['type'], parameters=row['params']))
    args.output.parent.mkdir(parents=True, exist_ok=True)
    with args.output.with_suffix('.csv').open('w', newline='', encoding='utf-8') as output:
        writer = csv.DictWriter(output, fieldnames=report[0].keys())
        writer.writeheader()
        writer.writerows(report)
    counts = Counter(row['status'] for row in report)
    groups = Counter(row['area'] for row in report)
    disabled = sum(row['entry'] in ('Function', 'Variable') and row['status'] != '+' for row in rows)
    changes = [name for name in sorted(symbols.keys() & baseline.keys())
               if any(symbols[name][key] != baseline[name][key] for key in ('entry', 'type', 'params'))]
    lines = [f'# ARM FAP API {version} coverage', '',
             'Generated by `python tools/audit_arm_fap_api.py` from the user-supplied SDK inventory.', '',
             f'- {len(symbols)} exported symbols: ' + ', '.join(f'{n} {k}' for k, n in counts.items()) + '.',
             f'- {disabled} disabled functions/variables excluded; headers are not runtime exports.',
             f'- All {len(supported)} bridged declarations match API {previous}.',
             '- Matching declarations do not verify enum values, structure layouts or behavior.',
             '- Native exports are implementation candidates, not callable ARM functions.',
             '- Bridged APIs retain the limits documented in the ARM runtime README.',
             '- No function is treated as supported merely because its name exists in the CSV.', '',
             '| Area | Exported symbols |', '| --- | ---: |']
    lines += [f'| {name} | {count} |' for name, count in sorted(groups.items())]
    lines += ['', f'## Changes since {previous}', '',
              f'Added: {len(symbols.keys() - baseline.keys())}; removed: {len(baseline.keys() - symbols.keys())}; changed declarations: {len(changes)}.', '',
              'Changed/removed symbols need an ABI review before a bridge can span these versions:', '']
    lines += [f'- `{name}`' for name in sorted(set(changes) | (baseline.keys() - symbols.keys()))]
    lines += ['', '## Next implementation groups', '',
              '1. Bounded C memory/string operations and integer helpers, tested against ARM behavior.',
              '2. FuriString, canvas/elements, submenu/widget and scene callbacks with opaque handles.',
              '3. Storage and FlipperFormat with guest structure conversion and exit cleanup.',
              '4. Queues, timers and guest scheduling before apps that create workers.',
              '5. Peripheral APIs individually, based on the hardware actually present on T-Embed.',
              '', 'CPU instruction coverage, ELF relocations and API bridges are separate requirements.',
              'Direct STM32 register access cannot use a normal API bridge. Four physical keys also',
              'require an explicit mapping for apps that rely on Left/Right. This report does not',
              'claim compatibility with every FAP.', '',
              f'SDK SHA-256: `{hashlib.sha256(args.sdk.read_bytes()).hexdigest()}`.', '']
    args.output.with_suffix('.md').write_text('\n'.join(lines), encoding='utf-8')
    print(f'API {version}: {len(symbols)} exports; {dict(counts)}; {len(supported)} bridge declarations verified against {previous}.')


if __name__ == '__main__':
    main()
