#!/usr/bin/env python3
"""Generate components/assets/assets_icon_paths.c.

Asset packs replace icons by path: a pack ships Icons/<path>.bmx (static) or
Icons/<path>/frame_NN.bm (animated), where <path> is the icon's location in the
upstream asset tree, such as "Interface/Lockscreen". Momentum generates that
mapping during its build; this port ships assets_icons.c pre-generated and has
no asset build step, so the table is generated here instead.

Icons whose names do not exist upstream are skipped. That is expected: this
port splits some upstream frame directories into separate per-frame icons
(A_Levelup1_128x64, I_hourglass0_24x24, ...) which no Momentum pack targets.

Usage:
    python tools/gen_icon_paths.py [--check]
"""

import argparse
import pathlib
import re
import sys

HEADER = """\
/* Generated by tools/gen_icon_paths.py -- do not edit by hand.
 *
 * Maps each compiled icon to its path within an asset pack's Icons directory,
 * so asset_packs_init() can look for a replacement. Paths match the upstream
 * Momentum asset tree so packs authored for Momentum apply unchanged. */

#include <assets_icons.h>

const IconPath ICON_PATHS[] = {
"""

FOOTER = """\
};

const size_t ICON_PATHS_COUNT = sizeof(ICON_PATHS) / sizeof(ICON_PATHS[0]);
"""


def build_index(icons_root):
    """Map an icon's bare name to its pack-relative path, without extension."""
    index = {}
    for path in sorted(icons_root.rglob("*")):
        if path.is_dir():
            # An animated icon upstream is a directory of frame_NN.png files.
            if any(path.glob("frame_*.png")):
                index.setdefault(path.name, path.relative_to(icons_root).as_posix())
        elif path.suffix == ".png" and path.parent != icons_root:
            relative = path.relative_to(icons_root).with_suffix("").as_posix()
            index.setdefault(path.stem, relative)
    return index


def generate(repo, momentum_root):
    header_text = (repo / "components/assets/assets_icons.h").read_text()
    names = re.findall(r"extern const Icon ([IA]_\w+);", header_text)

    index = build_index(momentum_root / "assets/icons")

    lines = []
    skipped = []
    for name in names:
        bare = name[2:]
        if bare in index:
            lines.append(f'    {{&{name}, "{index[bare]}"}},\n')
        else:
            skipped.append(name)

    return HEADER + "".join(lines) + FOOTER, len(lines), skipped


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the generated file is out of date instead of writing it",
    )
    args = parser.parse_args()

    repo = pathlib.Path(__file__).resolve().parents[1]
    momentum_root = repo.parent / "Momentum-Firmware"
    if not (momentum_root / "assets/icons").is_dir():
        print(f"error: upstream assets not found at {momentum_root}", file=sys.stderr)
        return 1

    target = repo / "components/assets/assets_icon_paths.c"
    text, count, skipped = generate(repo, momentum_root)

    if args.check:
        current = target.read_text() if target.is_file() else ""
        if current != text:
            print(f"error: {target.name} is out of date; re-run without --check", file=sys.stderr)
            return 1
        print(f"{target.name} is up to date ({count} icons)")
        return 0

    target.write_text(text)
    print(f"wrote {target.relative_to(repo)}: {count} icons mapped, {len(skipped)} skipped")
    if skipped:
        print("  skipped (not present upstream): " + ", ".join(skipped[:6]) +
              (" ..." if len(skipped) > 6 else ""))
    return 0


if __name__ == "__main__":
    sys.exit(main())
